name: npm-publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: '14.x'
      - name: Npm Install
        run: npm ci --silent
      - name: Build
        run: npm build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
