name: Lint & Build Check

on: push

jobs:
  install:
    name: Npm Install
    runs-on: ubuntu-latest
    steps:
      - name: Check out the git branch
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Zip node_modules
        run: zip -9qry "node_modules.zip" "./" -i "node_modules/*" -i "*/node_modules/*"
      - name: Upload node_modules.zip
        uses: actions/upload-artifact@v2
        with:
          name: node_modules.zip
          path: node_modules.zip

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Download node_modules.zip
        uses: actions/download-artifact@v2
        with:
          name: node_modules.zip
      - name: Unzip node_modules.zip
        run: unzip -q node_modules.zip
      - run: npm run lint
      - run: npm run build
      - name: Zip lib/node_modules
        run: zip -9qry "build.zip" "./" -i "node_modules/*" -i "*/node_modules/*" -i "lib/*"
      - name: Upload build.zip
        uses: actions/upload-artifact@v2
        with:
          name: build.zip
          path: build.zip

  lint:
    needs: build
    name: Lint
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Download build.zip
        uses: actions/download-artifact@v2
        with:
          name: build.zip
      - name: Unzip build.zip
        run: unzip -q build.zip
      - name: Lint
        run: npm run lint

  build-check:
    needs: build
    name: Build Check
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Download build.zip
        uses: actions/download-artifact@v2
        with:
          name: build.zip
      - name: Unzip build.zip
        run: unzip -q build.zip
      - name: Build Check
        run: npm run build:check
